import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import RTQueryClient from "@/lib/components/wrappers/RTQueryClient";
import { MUIThemeProvider } from "@/lib/components/wrappers/MuiThemeProvide";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RTQueryClient>
          <MUIThemeProvider>
            <ToastContainer position="bottom-left" autoClose={1000} />
            {children}
          </MUIThemeProvider>
        </RTQueryClient>
      </body>
    </html>
  );
}
