import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RTQueryClient from "@/lib/components/wrappers/RTQueryClient";
import { MUIThemeProvider } from "@/lib/components/wrappers/MuiThemeProvide";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RTQueryClient>
          <MUIThemeProvider>{children}</MUIThemeProvider>
        </RTQueryClient>
      </body>
    </html>
  );
}
